<?xml version="1.0" encoding="UTF-8"?>
<wsdl:description name="servicemix-exec"
                  targetNamespace="http://servicemix.apache.org/exec"
                  xmlns:wsdl="http://www.w3.org/2006/01/wsdl"
                  xmlns:tns="http://servicemix.apache.org/exec"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                  
    <wsdl:description>
        Abstract WSDL for the servicemix-exec component.
    </wsdl:description>                  
    
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   targetNamespace="http://servicemix.apache.org/exec"
                   xmlns="http://servicemix.apache.org/exec">
            
            <xs:element name="Command" type="xs:string"/>
            
            <xs:element name="ExecutionData" type="TypeExecutionData"/>
            <xs:complexType name="TypeExecutionData">
                <xs:sequence>
                    <xs:element name="output" type="xs:string"/>
                    <xs:element name="error" type="xs:string"/>
                    <xs:element name="returnCode" type="xs:integer"/>                
                </xs:sequence>    
            </xs:complexType>
                       
        </xs:schema>
    </wsdl:types>
    
    <wsdl:interfaces>
        <wsdl:interface name="executeInterface">
            <wsdl:fault name="executionFault" element="xs:string"/>
            <wsdl:operation name="execute" pattern="http://www.w3.org/ns/wsdl/in-out"
                       style="http://www.w3.org/ns/wsdl/style/iri">
                <wsdl:input messageLabel="In" element="Command"/>
                <wsdl:output messageLabel="Out" element="ExecutionData"/>                       
            </wsdl:operation>                  
        </wsdl:interface>
    </wsdl:interfaces>
                  
</wsdl:description>               