<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="servicemix-exec"
                  targetNamespace="http://servicemix.apache.org/servicemix-exec"
                  xmlns="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap"
                  xmlns:tns="http://servicemix.apache.org/servicemix-exec"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema">           
                  
    <message name="ExecRequest">
        <part name="command" type="xsd:string"/>
    </message>
    <message name="ExecResponse">
        <part name="output" type="xsd:string"/>
    </message>
    
    <portType name="ExecPortType">
        <operation name="exec">
            <input message="tns:ExecRequest"/>
            <output message="tns:ExecResponse"/>
        </operation>
    </portType>
    
    <binding name="ExecBinding" type="ExecPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="exec">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation> 
    </binding>
    
    <service name="ExecService">
        <documentation>WSDL for ServiceMix Exec component</documentation>
        <port binding="tns:ExecBinding" name="ExecPort">
            <soap:address location="nmr://exec"/>
        </port>
    </service>
                  
</wsdl:definitions>                  